### ISSUE TITLE
Unable to set "Add to track"/"Remove from track" values (object is not iterable)

### ISSUE THREAD

**Issue by peyn** [AlexandrErohin/home-assistant-flightradar24#27]
Hi,

I get an error 95% of the time when I change the "Add to track" or "Remove from track" field values.
The error states that the TEXT/SET_VALUE service could not set the value because the "NoneType" object is not iterable.

Kind regards,
Mateusz

PS Great work on the integration! :-)

**Comment by AlexandrErohin** [comment]
@peyn Could you post errors from logs?

**Comment by peyn** [comment]
2024-04-03 11:10:29.059 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [546957093568] 'NoneType' object is not iterable
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 239, in handle_call_service
response = await hass.services.async_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2319, in async_call
response_data = await coro
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2356, in _execute_service
return await target(service_call)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 905, in entity_service_call
single_response = await _handle_entity_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in _handle_entity_call
result = await task
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/text/__init__.py", line 84, in _async_set_value
await entity.async_set_value(value)
File "/config/custom_components/flightradar24/text.py", line 76, in async_set_value
await self.entity_description.method(self.coordinator, value)
File "/config/custom_components/flightradar24/coordinator.py", line 79, in remove_track
for flight_id in self.tracked:
TypeError: 'NoneType' object is not iterable

**Comment by AlexandrErohin** [comment]
Fixed. Please try version 1.9.0

**Comment by peyn** [comment]
Hi,

Thank you, it's fixed.

Kind regards,
Mateusz
