### ISSUE TITLE
Unable to import component: cannot import name 'countries' from 'pycountry' (unknown location)

### ISSUE THREAD

**Issue by Sythsaz** [AlexandrErohin/home-assistant-flightradar24#87]
Running: 
    Core 2024.11.3
    Supervisor 2024.11.4
    Operating System
    Frontend 20241106.2 ⸱ legacy

and this happened during a reboot with it running fine just before hand

```Logger: homeassistant.setup
Source: setup.py:334
First occurred: 5:38:47 PM (1 occurrences)
Last logged: 5:38:47 PM

Setup failed for custom integration 'flightradar24': Unable to import component: cannot import name 'countries' from 'pycountry' (unknown location)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1011, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1071, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/flightradar24/__init__.py", line 7, in <module>
    from .coordinator import FlightRadar24Coordinator
  File "/config/custom_components/flightradar24/coordinator.py", line 8, in <module>
    from pycountry import countries
ImportError: cannot import name 'countries' from 'pycountry' (unknown location)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1031, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1023, in async_get_component
    comp = self._get_component()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1071, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/flightradar24/__init__.py", line 7, in <module>
    from .coordinator import FlightRadar24Coordinator
  File "/config/custom_components/flightradar24/coordinator.py", line 8, in <module>
    from pycountry import countries
ImportError: cannot import name 'countries' from 'pycountry' (unknown location)```

**Comment by Sythsaz** [comment]
After another restart it works again but I thought it should be posted none the less

**Comment by AlexandrErohin** [comment]
@Sythsaz Hi
Something happened with your first reboot - so why It had problem with importing a module
P.S. Would be great if you could give a star to the repo :) Thanks

**Comment by xhemp** [comment]
This just happened with me as well, out of the blue after a restart. HAOS / HA core 2024.12.5
