### ISSUE TITLE
Detected blocking call to import_module

### ISSUE THREAD

**Issue by Sythsaz** [AlexandrErohin/home-assistant-flightradar24#88]
Running:
    Core 2024.11.3
    Supervisor 2024.11.4
    Operating System
    Frontend 20241106.2 ⸱ legacy

```Logger: homeassistant.util.loop
Source: util/loop.py:77
First occurred: 5:38:47 PM (1 occurrences)
Last logged: 5:38:47 PM

Detected blocking call to import_module with args ('custom_components.flightradar24',) in /usr/src/homeassistant/homeassistant/loader.py, line 1071: ComponentProtocol, importlib.import_module(self.pkg_path) inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component component = await integration.async_get_component() File "/usr/src/homeassistant/homeassistant/loader.py", line 1023, in async_get_component comp = self._get_component() File "/usr/src/homeassistant/homeassistant/loader.py", line 1071, in _get_component ComponentProtocol, importlib.import_module(self.pkg_path)```

**Comment by AlexandrErohin** [comment]
@Sythsaz Hi.
Have you tried to reboot HA?

**Comment by Sythsaz** [comment]
@AlexandrErohin Sorry, it seems so far that a reboot has caused the error to disappear. I'll keep monitoring it here and see if that changes at all. Thanks for your time
